const products = [
  {
    _id: "1",
    name: "Solar Panels",
    image: "/images/solar01.jpg",
    description:
      "These are the most essential component of any solar power system. They convert sunlight into electricity and are available in various sizes and types",
    brand: "Solar LLC",
    category: "Electronics",
    price: 899.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: "2",
    name: "Solar Batteries",
    image: "/images/solar02.webp",
    description:
      "These are used to store the electricity generated by solar panels, ensuring that you have power even when the sun is not shining",
    brand: "Solar LLC",
    category: "Electronics",
    price: 214.99,
    countInStock: 7,
    rating: 4.0,
    numReviews: 8,
  },
  {
    _id: "3",
    name: "Solar Charge Controllers",
    image: "/images/solar03.jpeg",
    description:
      "These devices regulate the charging of solar batteries, preventing overcharging and prolonging the lifespan of your batteries",
    brand: "Solar LLC",
    category: "Electronics",
    price: 9.99,
    countInStock: 5,
    rating: 3,
    numReviews: 12,
  },
  {
    _id: "4",
    name: "Solar Inverters",
    image: "/images/solar04.jpeg",
    description:
      "These convert the DC (direct current) electricity generated by solar panels into AC (alternating current) electricity that can be used to power household appliances",
    brand: "Solar LLC",
    category: "Electronics",
    price: 399.99,
    countInStock: 11,
    rating: 5,
    numReviews: 12,
  },
  {
    _id: "5",
    name: "Solar Water Heaters",
    image: "/images/solar05.jpeg",
    description:
      "These use the sun's energy to heat water, reducing the amount of electricity or gas needed to do so",
    brand: "Solar LLC",
    category: "Electronics",
    price: 1199.99,
    countInStock: 7,
    rating: 4.5,
    numReviews: 10,
  },
  {
    _id: "6",
    name: "Solar Lights",
    image: "/images/solar06.jpg",
    description:
      "These are ideal for outdoor lighting, such as garden or security lights. They are powered by a small solar panel that charges during the day and illuminates at night",
    brand: "Solar LLC",
    category: "Electronics",
    price: 34.99,
    countInStock: 0,
    rating: 4,
    numReviews: 12,
  },
];

export default products;
